package com.hnqj.model;

public class Account {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_account.uid
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    private String uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_account.account
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    private String account;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_account.passwd
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    private String passwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_account.userid
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    private String userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_account.state
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    private Short state;


    private Short usertype;

    public Short getUsertype() {
        return usertype;
    }

    public void setUsertype(Short usertype) {
        this.usertype = usertype;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_account.usemobile
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    private Short usemobile;


    private String extend_1;
    private String extend_2;
    private String extend_3;
    private String extend_4;
    private String extend_5;
    private String extend_6;
    private String extend_7;
    private String extend_8;
    /**
     * 获取推荐码
     */
    public String getExtend_1()
    {
        return extend_1;
    }
    /**
     * 设置推荐码
     */
    public void setExtend_1(String value)
    {
        this.extend_1 = value;
    }
    /**
     * 获取生成二维码信息
     */
    public String getExtend_2()
    {
        return extend_2;
    }
    /**
     * 设置生成二维码信息
     */
    public void setExtend_2(String value)
    {
        this.extend_2 = value;
    }
    /**
     * 获取扩展备用
     */
    public String getExtend_3()
    {
        return extend_3;
    }
    /**
     * 设置扩展备用
     */
    public void setExtend_3(String value)
    {
        this.extend_3 = value;
    }
    /**
     * 获取扩展备用
     */
    public String getExtend_4()
    {
        return extend_4;
    }
    /**
     * 设置扩展备用
     */
    public void setExtend_4(String value)
    {
        this.extend_4 = value;
    }
    /**
     * 获取扩展备用
     */
    public String getExtend_5()
    {
        return extend_5;
    }
    /**
     * 设置扩展备用
     */
    public void setExtend_5(String value)
    {
        this.extend_5 = value;
    }
    /**
     * 获取扩展备用
     */
    public String getExtend_6()
    {
        return extend_6;
    }
    /**
     * 设置扩展备用
     */
    public void setExtend_6(String value)
    {
        this.extend_6 = value;
    }
    /**
     * 获取扩展备用
     */
    public String getExtend_7()
    {
        return extend_7;
    }
    /**
     * 设置扩展备用
     */
    public void setExtend_7(String value)
    {
        this.extend_7 = value;
    }
    /**
     * 获取扩展备用
     */
    public String getExtend_8()
    {
        return extend_8;
    }
    /**
     * 设置扩展备用
     */
    public void setExtend_8(String value)
    {
        this.extend_8 = value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_account.uid
     *
     * @return the value of tb_account.uid
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_account.uid
     *
     * @param uid the value for tb_account.uid
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_account.account
     *
     * @return the value of tb_account.account
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_account.account
     *
     * @param account the value for tb_account.account
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_account.passwd
     *
     * @return the value of tb_account.passwd
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public String getPasswd() {
        return passwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_account.passwd
     *
     * @param passwd the value for tb_account.passwd
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public void setPasswd(String passwd) {
        this.passwd = passwd == null ? null : passwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_account.userid
     *
     * @return the value of tb_account.userid
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_account.userid
     *
     * @param userid the value for tb_account.userid
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_account.state
     *
     * @return the value of tb_account.state
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public Short getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_account.state
     *
     * @param state the value for tb_account.state
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public void setState(Short state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_account.usemobile
     *
     * @return the value of tb_account.usemobile
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public Short getUsemobile() {
        return usemobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_account.usemobile
     *
     * @param usemobile the value for tb_account.usemobile
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public void setUsemobile(Short usemobile) {
        this.usemobile = usemobile;
    }

}