package com.hnqj.model;

import java.util.Date;

public class Graph {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_graph.uid
     *
     * @mbg.generated Fri Mar 02 17:26:19 CST 2018
     */
    private String uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_graph.addtime
     *
     * @mbg.generated Fri Mar 02 17:26:19 CST 2018
     */
    private Date addtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_graph.enclosureurl
     *
     * @mbg.generated Fri Mar 02 17:26:19 CST 2018
     */
    private String enclosureurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_graph.favcount
     *
     * @mbg.generated Fri Mar 02 17:26:19 CST 2018
     */
    private Integer favcount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_graph.displayflag
     *
     * @mbg.generated Fri Mar 02 17:26:19 CST 2018
     */
    private String displayflag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_graph.delflag
     *
     * @mbg.generated Fri Mar 02 17:26:19 CST 2018
     */
    private String delflag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_graph.checkuser
     *
     * @mbg.generated Fri Mar 02 17:26:19 CST 2018
     */
    private String checkuser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_graph.chacktime
     *
     * @mbg.generated Fri Mar 02 17:26:19 CST 2018
     */
    private Date chacktime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_graph.userid
     *
     * @mbg.generated Fri Mar 02 17:26:19 CST 2018
     */
    private String userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_graph.ticknums
     *
     * @mbg.generated Fri Mar 02 17:26:19 CST 2018
     */
    private Integer ticknums;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_graph.graphtype
     *
     * @mbg.generated Fri Mar 02 17:26:19 CST 2018
     */
    private String graphtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_graph.graphclassification
     *
     * @mbg.generated Fri Mar 02 17:26:19 CST 2018
     */
    private String graphclassification;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_graph.graphtitle
     *
     * @mbg.generated Fri Mar 02 17:26:19 CST 2018
     */
    private String graphtitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_graph.graphdetail
     *
     * @mbg.generated Fri Mar 02 17:26:19 CST 2018
     */
    private String graphdetail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_graph.solicitationtype
     *
     * @mbg.generated Fri Mar 02 17:26:19 CST 2018
     */
    private Integer solicitationtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_graph.moneyreward
     *
     * @mbg.generated Fri Mar 02 17:26:19 CST 2018
     */
    private Double moneyreward;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_graph.endtime
     *
     * @mbg.generated Fri Mar 02 17:26:19 CST 2018
     */
    private Date endtime;

    private Integer state;

    private Integer submissionnums;

    private String bidsubmission;

    private Date graphendtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_graph.uid
     *
     * @return the value of tb_graph.uid
     *
     * @mbg.generated Fri Mar 02 17:26:19 CST 2018
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_graph.uid
     *
     * @param uid the value for tb_graph.uid
     *
     * @mbg.generated Fri Mar 02 17:26:19 CST 2018
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_graph.addtime
     *
     * @return the value of tb_graph.addtime
     *
     * @mbg.generated Fri Mar 02 17:26:19 CST 2018
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_graph.addtime
     *
     * @param addtime the value for tb_graph.addtime
     *
     * @mbg.generated Fri Mar 02 17:26:19 CST 2018
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_graph.enclosureurl
     *
     * @return the value of tb_graph.enclosureurl
     *
     * @mbg.generated Fri Mar 02 17:26:19 CST 2018
     */
    public String getEnclosureurl() {
        return enclosureurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_graph.enclosureurl
     *
     * @param enclosureurl the value for tb_graph.enclosureurl
     *
     * @mbg.generated Fri Mar 02 17:26:19 CST 2018
     */
    public void setEnclosureurl(String enclosureurl) {
        this.enclosureurl = enclosureurl == null ? null : enclosureurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_graph.favcount
     *
     * @return the value of tb_graph.favcount
     *
     * @mbg.generated Fri Mar 02 17:26:19 CST 2018
     */
    public Integer getFavcount() {
        return favcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_graph.favcount
     *
     * @param favcount the value for tb_graph.favcount
     *
     * @mbg.generated Fri Mar 02 17:26:19 CST 2018
     */
    public void setFavcount(Integer favcount) {
        this.favcount = favcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_graph.displayflag
     *
     * @return the value of tb_graph.displayflag
     *
     * @mbg.generated Fri Mar 02 17:26:19 CST 2018
     */
    public String getDisplayflag() {
        return displayflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_graph.displayflag
     *
     * @param displayflag the value for tb_graph.displayflag
     *
     * @mbg.generated Fri Mar 02 17:26:19 CST 2018
     */
    public void setDisplayflag(String displayflag) {
        this.displayflag = displayflag == null ? null : displayflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_graph.delflag
     *
     * @return the value of tb_graph.delflag
     *
     * @mbg.generated Fri Mar 02 17:26:19 CST 2018
     */
    public String getDelflag() {
        return delflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_graph.delflag
     *
     * @param delflag the value for tb_graph.delflag
     *
     * @mbg.generated Fri Mar 02 17:26:19 CST 2018
     */
    public void setDelflag(String delflag) {
        this.delflag = delflag == null ? null : delflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_graph.checkuser
     *
     * @return the value of tb_graph.checkuser
     *
     * @mbg.generated Fri Mar 02 17:26:19 CST 2018
     */
    public String getCheckuser() {
        return checkuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_graph.checkuser
     *
     * @param checkuser the value for tb_graph.checkuser
     *
     * @mbg.generated Fri Mar 02 17:26:19 CST 2018
     */
    public void setCheckuser(String checkuser) {
        this.checkuser = checkuser == null ? null : checkuser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_graph.chacktime
     *
     * @return the value of tb_graph.chacktime
     *
     * @mbg.generated Fri Mar 02 17:26:19 CST 2018
     */
    public Date getChacktime() {
        return chacktime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_graph.chacktime
     *
     * @param chacktime the value for tb_graph.chacktime
     *
     * @mbg.generated Fri Mar 02 17:26:19 CST 2018
     */
    public void setChacktime(Date chacktime) {
        this.chacktime = chacktime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_graph.userid
     *
     * @return the value of tb_graph.userid
     *
     * @mbg.generated Fri Mar 02 17:26:19 CST 2018
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_graph.userid
     *
     * @param userid the value for tb_graph.userid
     *
     * @mbg.generated Fri Mar 02 17:26:19 CST 2018
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_graph.ticknums
     *
     * @return the value of tb_graph.ticknums
     *
     * @mbg.generated Fri Mar 02 17:26:19 CST 2018
     */
    public Integer getTicknums() {
        return ticknums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_graph.ticknums
     *
     * @param ticknums the value for tb_graph.ticknums
     *
     * @mbg.generated Fri Mar 02 17:26:19 CST 2018
     */
    public void setTicknums(Integer ticknums) {
        this.ticknums = ticknums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_graph.graphtype
     *
     * @return the value of tb_graph.graphtype
     *
     * @mbg.generated Fri Mar 02 17:26:19 CST 2018
     */
    public String getGraphtype() {
        return graphtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_graph.graphtype
     *
     * @param graphtype the value for tb_graph.graphtype
     *
     * @mbg.generated Fri Mar 02 17:26:19 CST 2018
     */
    public void setGraphtype(String graphtype) {
        this.graphtype = graphtype == null ? null : graphtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_graph.graphclassification
     *
     * @return the value of tb_graph.graphclassification
     *
     * @mbg.generated Fri Mar 02 17:26:19 CST 2018
     */
    public String getGraphclassification() {
        return graphclassification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_graph.graphclassification
     *
     * @param graphclassification the value for tb_graph.graphclassification
     *
     * @mbg.generated Fri Mar 02 17:26:19 CST 2018
     */
    public void setGraphclassification(String graphclassification) {
        this.graphclassification = graphclassification == null ? null : graphclassification.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_graph.graphtitle
     *
     * @return the value of tb_graph.graphtitle
     *
     * @mbg.generated Fri Mar 02 17:26:19 CST 2018
     */
    public String getGraphtitle() {
        return graphtitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_graph.graphtitle
     *
     * @param graphtitle the value for tb_graph.graphtitle
     *
     * @mbg.generated Fri Mar 02 17:26:19 CST 2018
     */
    public void setGraphtitle(String graphtitle) {
        this.graphtitle = graphtitle == null ? null : graphtitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_graph.graphdetail
     *
     * @return the value of tb_graph.graphdetail
     *
     * @mbg.generated Fri Mar 02 17:26:19 CST 2018
     */
    public String getGraphdetail() {
        return graphdetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_graph.graphdetail
     *
     * @param graphdetail the value for tb_graph.graphdetail
     *
     * @mbg.generated Fri Mar 02 17:26:19 CST 2018
     */
    public void setGraphdetail(String graphdetail) {
        this.graphdetail = graphdetail == null ? null : graphdetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_graph.solicitationtype
     *
     * @return the value of tb_graph.solicitationtype
     *
     * @mbg.generated Fri Mar 02 17:26:19 CST 2018
     */
    public Integer getSolicitationtype() {
        return solicitationtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_graph.solicitationtype
     *
     * @param solicitationtype the value for tb_graph.solicitationtype
     *
     * @mbg.generated Fri Mar 02 17:26:19 CST 2018
     */
    public void setSolicitationtype(Integer solicitationtype) {
        this.solicitationtype = solicitationtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_graph.moneyreward
     *
     * @return the value of tb_graph.moneyreward
     *
     * @mbg.generated Fri Mar 02 17:26:19 CST 2018
     */
    public Double getMoneyreward() {
        return moneyreward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_graph.moneyreward
     *
     * @param moneyreward the value for tb_graph.moneyreward
     *
     * @mbg.generated Fri Mar 02 17:26:19 CST 2018
     */
    public void setMoneyreward(Double moneyreward) {
        this.moneyreward = moneyreward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_graph.endtime
     *
     * @return the value of tb_graph.endtime
     *
     * @mbg.generated Fri Mar 02 17:26:19 CST 2018
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_graph.endtime
     *
     * @param endtime the value for tb_graph.endtime
     *
     * @mbg.generated Fri Mar 02 17:26:19 CST 2018
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    public Integer getState() {
        return state;
    }

    public void setState(Integer state) {
        this.state = state;
    }

    public Integer getSubmissionnums() {
        return submissionnums;
    }

    public void setSubmissionnums(Integer submissionnums) {
        this.submissionnums = submissionnums;
    }

    public String getBidsubmission() {
        return bidsubmission;
    }

    public void setBidsubmission(String bidsubmission) {
        this.bidsubmission = bidsubmission;
    }

    public Date getGraphendtime() {
        return graphendtime;
    }

    public void setGraphendtime(Date graphendtime) {
        this.graphendtime = graphendtime;
    }
}