package com.hnqj.model;

import java.io.Serializable;

public class Userinfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_userinfo.uid
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    private String uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_userinfo.fristname
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    private String fristname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_userinfo.telephone
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    private String telephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_userinfo.iccode
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    private String iccode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_userinfo.usrpicurl
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    private String usrpicurl;

    private String smname;
    private String email;
    private String qqid;
    private String msnid;
    private String ofphone;
    private String zhiye;
    private String label;
    private String address;
    private String weibo;
    private String bankcode;
    private String bankaddr;
    private String sex;
    private String sfzdate;

    private String idpic;

    private Integer bidnums;

    private double winningbid;



    public String getIdpic() {
        return idpic;
    }

    public void setIdpic(String idpic) {
        this.idpic = idpic;
    }

    private String idpicback;
    public String getIdpicback() {
        return idpicback;
    }

    public void setIdpicback(String idpicback) {
        this.idpicback = idpicback;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_userinfo.uid
     *
     * @return the value of tb_userinfo.uid
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_userinfo.uid
     *
     * @param uid the value for tb_userinfo.uid
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_userinfo.fristname
     *
     * @return the value of tb_userinfo.fristname
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public String getFristname() {
        return fristname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_userinfo.fristname
     *
     * @param fristname the value for tb_userinfo.fristname
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public void setFristname(String fristname) {
        this.fristname = fristname == null ? null : fristname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_userinfo.telephone
     *
     * @return the value of tb_userinfo.telephone
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_userinfo.telephone
     *
     * @param telephone the value for tb_userinfo.telephone
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_userinfo.iccode
     *
     * @return the value of tb_userinfo.iccode
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public String getIccode() {
        return iccode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_userinfo.iccode
     *
     * @param iccode the value for tb_userinfo.iccode
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public void setIccode(String iccode) {
        this.iccode = iccode == null ? null : iccode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_userinfo.usrpicurl
     *
     * @return the value of tb_userinfo.usrpicurl
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public String getUsrpicurl() {
        return usrpicurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_userinfo.usrpicurl
     *
     * @param usrpicurl the value for tb_userinfo.usrpicurl
     *
     * @mbg.generated Sun Nov 12 10:54:35 CST 2017
     */
    public void setUsrpicurl(String usrpicurl) {
        this.usrpicurl = usrpicurl == null ? null : usrpicurl.trim();
    }

    /**
     * 获取昵称
     */
    public String getSmname()
    {
        return smname==null?"":smname;
    }
    /**
     * 设置昵称
     */
    public void setSmname(String value)
    {
        this.smname = value;
    }
    /**
     * 获取email
     */
    public String getEmail()
    {
        return email;
    }
    /**
     * 设置email
     */
    public void setEmail(String value)
    {
        this.email = value;
    }
    /**
     * 获取qq
     */
    public String getQqid()
    {
        return qqid;
    }
    /**
     * 设置qq
     */
    public void setQqid(String value)
    {
        this.qqid = value;
    }
    /**
     * 获取msn
     */
    public String getMsnid()
    {
        return msnid;
    }
    /**
     * 设置msn
     */
    public void setMsnid(String value)
    {
        this.msnid = value;
    }
    /**
     * 获取固定电话
     */
    public String getOfphone()
    {
        return ofphone;
    }
    /**
     * 设置固定电话
     */
    public void setOfphone(String value)
    {
        this.ofphone = value;
    }
    /**
     * 获取职业
     */
    public String getZhiye()
    {
        return zhiye;
    }
    /**
     * 设置职业
     */
    public void setZhiye(String value)
    {
        this.zhiye = value;
    }
    /**
     * 获取标签
     */
    public String getLabel()
    {
        return label;
    }
    /**
     * 设置标签
     */
    public void setLabel(String value)
    {
        this.label = value;
    }
    /**
     * 获取联系地址
     */
    public String getAddress()
    {
        return address;
    }
    /**
     * 设置联系地址
     */
    public void setAddress(String value)
    {
        this.address = value;
    }
    /**
     * 获取微博
     */
    public String getWeibo()
    {
        return weibo;
    }
    /**
     * 设置微博
     */
    public void setWeibo(String value)
    {
        this.weibo = value;
    }
    /**
     * 获取银行卡号
     */
    public String getBankcode()
    {
        return bankcode;
    }
    /**
     * 设置银行卡号
     */
    public void setBankcode(String value)
    {
        this.bankcode = value;
    }
    /**
     * 获取开户行
     */
    public String getBankaddr()
    {
        return bankaddr;
    }
    /**
     * 设置开户行
     */
    public void setBankaddr(String value)
    {
        this.bankaddr = value;
    }
    /**
     * 获取性别
     */
    public String getSex()
    {
        return sex;
    }
    /**
     * 设置性别
     */
    public void setSex(String value)
    {
        this.sex = value;
    }
    /**
     * 获取身份证有效期
     */
    public String getSfzdate()
    {
        return sfzdate;
    }
    /**
     * 设置身份证有效期
     */
    public void setSfzdate(String value)
    {
        this.sfzdate = value;
    }

    public Integer getBidnums() {
        return bidnums;
    }

    public void setBidnums(Integer bidnums) {
        this.bidnums = bidnums;
    }

    public double getWinningbid() {
        return winningbid;
    }

    public void setWinningbid(double winningbid) {
        this.winningbid = winningbid;
    }
}